spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.99.213:3306/myblogs?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.xa.DruidXADataSource

  redis:
      open: true  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 139.199.99.213
      port: 6379
      password:       # 密码（默认为空）
      timeout: 30000  # 连接超时时长（毫秒）
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接    # 连接池中的最小空闲连接



mybatis:
  type-aliases-package: com.sushuzhuang.myblogs.domain
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

classPath:
  uploadImg: G:\\IdeaProjects\\myblogs\\src\\main\\resources\\templates\\images\\deatils